//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_password { get; set; }
        public int admin_state { get; set; }
        public string kuser { get; set; }
        public Nullable<System.DateTime> kdate { get; set; }
        public string muser { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
    }
}
