//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int article_id { get; set; }
        public string article_title { get; set; }
        public string article_click_url { get; set; }
        public int article_sort { get; set; }
        public int article_state { get; set; }
        public string article_kuser { get; set; }
        public System.DateTime article_kdate { get; set; }
        public string article_muser { get; set; }
        public System.DateTime article_mdate { get; set; }
        public string article_cover_image { get; set; }
        public int category_id { get; set; }
        public string article_keywords { get; set; }
        public string article_author { get; set; }
        public string article_description { get; set; }
        public string article_content { get; set; }
    }
}
