//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTicks
    {
        public int at_id { get; set; }
        public string at_ipfrom { get; set; }
        public string at_brower { get; set; }
        public string at_device { get; set; }
        public string at_kuser { get; set; }
        public System.DateTime at_kdate { get; set; }
        public int article_id { get; set; }
    }
}
