//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleCategory
    {
        public int category_id { get; set; }
        public string category_name { get; set; }
        public int category_father_id { get; set; }
        public int category_sort { get; set; }
        public int category_type { get; set; }
        public string category_type_name { get; set; }
        public string category_code { get; set; }
        public int category_state { get; set; }
        public Nullable<int> category_level { get; set; }
    }
}
