//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaomingXuanShou
    {
        public int p_id { get; set; }
        public string Name { get; set; }
        public string ChuShengRiQi { get; set; }
        public string NianJi { get; set; }
        public string LianXiDianHua { get; set; }
        public string YouXiang { get; set; }
        public string suoShuFenLei { get; set; }
        public string ZuoPinXuHao { get; set; }
        public string XingQuAiHao { get; set; }
        public string Xuexiao { get; set; }
        public string CannSaiZuoPin { get; set; }
        public string CanSaiLeiBie { get; set; }
        public string CanSaiJingLi { get; set; }
        public string SuoHuoRongYu { get; set; }
        public string HuoDongShiJian { get; set; }
        public string MengXiangZhiYe { get; set; }
        public Nullable<int> state { get; set; }
    }
}
