//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChineseCultureDBEntities : DbContext
    {
        public ChineseCultureDBEntities()
            : base("name=ChineseCultureDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<admin_login_log> admin_login_log { get; set; }
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<friend_link> friend_link { get; set; }
        public virtual DbSet<article_category> article_category { get; set; }
        public virtual DbSet<article_type> article_type { get; set; }
        public virtual DbSet<function> function { get; set; }
    }
}
