//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendLink
    {
        public int fl_id { get; set; }
        public string fl_title { get; set; }
        public string fl_url { get; set; }
        public string fl_state { get; set; }
        public int fl_sort { get; set; }
        public System.DateTime fl_kdate { get; set; }
        public string fl_kuer { get; set; }
    }
}
