//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class function
    {
        public int function_id { get; set; }
        public int function_father_id { get; set; }
        public string function_name { get; set; }
        public int function_category { get; set; }
        public int function_site { get; set; }
        public int function_state { get; set; }
        public System.DateTime kdate { get; set; }
        public string kuser { get; set; }
    }
}
