//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int member_id { get; set; }
        public string member_name { get; set; }
        public string member_password { get; set; }
        public int member_state { get; set; }
        public string kuser { get; set; }
        public System.DateTime kdate { get; set; }
        public string muser { get; set; }
        public System.DateTime mdate { get; set; }
        public string member_nickname { get; set; }
    }
}
