//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMenu
    {
        public int menu_id { get; set; }
        public string menu_name { get; set; }
        public string menu_code { get; set; }
        public string site_id { get; set; }
        public int menu_state { get; set; }
        public string menu_category { get; set; }
    }
}
