//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCulture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string user_telephone { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public int user_state { get; set; }
        public System.DateTime user_regdate { get; set; }
        public string user_generate_code { get; set; }
    }
}
